 const Bestsellerdata = [
    {
        id:0,
        url:'/alexa.png',
        category:'Gadgets'
    },
    {
        id:1,
        url:'/tshirtone.png',
        category:'Cloths'
    },
    {
        id:2,
        url:'/bagtwo.png',
        category:'Bags'
    },
    {
        id:3,
        url:'/headphonethree.png',
        category:'Headphones'
    },
    {
        id:4,
        url:'/tshirttwo.png',
        category:'Cloths'
    },
    {
        id:5,
        url:'/shoeone.png',
        category:'Shoes'
    },
    {
        id:6,
        url:'/cosmeticone.png',
        category:'Beauty&Cosmetic'
    }
 ]

 export default Bestsellerdata;